Update Chinese language files
digao-dalpiaz/DigaoDesk pull request #31
Opened 2022-07-06 02:15 UTC by wcxu21

Update Chinese language files

2022-07-06 13:54 UTC, digao-dalpiaz requested changes
Hello, please review some missing tags

2022-07-06 13:54 UTC, digao-dalpiaz commented on DigaoDeskApp/Languages/lang_chinese.json
> +  "Config_Tab_Logs": "日志",
Missing "Config_Tab_General" var

2022-07-06 13:54 UTC, digao-dalpiaz commented on DigaoDeskApp/Languages/lang_chinese.json
> +  "Config_Logs_Font": "字体",
Missing:
Config_General_Language
Config_General_LanguageInfo

2022-07-06 13:54 UTC, digao-dalpiaz commented on DigaoDeskApp/Languages/lang_chinese.json
> +
Missing:
Config_InvalidLanguage
Config_GitRepositoryNotFound

2022-07-07 00:52 UTC, wcxu21 commented
Update Chinese translation

2022-07-07 02:01 UTC, digao-dalpiaz approved these changes
ok

2022-07-07 02:02 UTC, merged